name: finmentor
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  shadcn_ui: ^0.19.3
  flashy_tab_bar2: ^0.0.10
  adaptive_theme: ^3.6.0

  # Sign in
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  # State Management
  flutter_bloc: ^9.1.0
  #bloc: ^9.0.0
  get: ^4.6.6
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Firebase
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0

  # Utils
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  package_info_plus: ^8.1.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  path_provider: ^2.1.5
  rflutter_alert: ^2.0.7

  # Analytics
  posthog_flutter: ^4.8.0
  flutter_branch_sdk: ^8.3.1

  # Push Notifications
  onesignal_flutter: ^5.2.9

  # Translations
  azbox: ^1.0.8

  # Onboarding
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/launcher/
    - assets/fonts/